#!/bin/sh /etc/rc.common

START=90

start() {
	config_load "oscam"
	config_get enable config enable
	config_get interval config interval

	enable=$(uci get oscam.config.enable)
	echo "game  start....."
	oscamcron

	[ $enable -eq 0 ] && exit 0
	/usr/bin/oscam -b -c /etc/oscam
	echo "oscam start ....."
}

oscamcron() {

interval=$(uci get oscam.config.interval)
oscam_cron=`cat /etc/crontabs/root | grep "/etc/init.d/oscam restart"`
if  [ "$enable" == "1" -a "$interval" != "0" ]; then 
	oscam_new="*/${interval} * * * * /etc/init.d/oscam restart"
	if [ "z${oscam_cron}" != "z${oscam_new}" ] ; then
		cat /etc/crontabs/root | grep -v "/etc/init.d/oscam restart" > /tmp/crontabs_oscam
		echo "" >> /tmp/crontabs_oscam
		echo "*/${interval} * * * * /etc/init.d/oscam restart" >> /tmp/crontabs_oscam
		cat /tmp/crontabs_oscam | grep -v ^$ > /etc/crontabs/root
		/etc/init.d/cron restart
	fi
else
	if [ "z${oscam_cron}" != "z" ] ; then
		cat /etc/crontabs/root | grep -v "/etc/init.d/oscam restart" > /tmp/crontabs_oscam
		cat /tmp/crontabs_oscam | grep -v ^$ > /etc/crontabs/root
		/etc/init.d/cron restart
	fi
fi
rm -f /tmp/crontabs_oscam
}

stop() {
	killall -9 oscam
	echo "oscam stopped"
}

restart() {
	stop
	start
}
